src/detail-panels/block-panel-generic/block-panel-generic.js
https://github.com/user-attachments/assets/0893d6f8-a110-4516-9a15-dc997c44965e
=> UI: Change icon on table view toggle

.github/workflows/npm.yaml, package-lock.json, package.json, readme.md, src/api/throttled-async-cache.js, src/detail-panels/account-header/account-header.js, src/detail-panels/history/post/post-embed.js, src/detail-panels/history/post/render-post.js, src/detail-panels/history/search/apply-search.js, src/detail-panels/lists/lists.js, src/landing/home-stats/home-stats-table.js, src/landing/search-autocomplete/search-autocomplete.js, tsconfig.json
Also can check via `npm test` so we don't have to rely on people's IDEs always catching everything.
To facilitate this getting in and prevent me from breaking anything I @ts-ignore'd errors rather than trying to fix them myself.
=> Gh actions

src/api/handle-history.js, src/detail-panels/layout.js
Closes #111 
third try, last one got closed out during the repo migration
@thieflord06
=> Fix handle history

src/api/handle-history.js, src/detail-panels/account-resolver.js, src/detail-panels/block-panel-generic/block-panel-generic.js, src/detail-panels/layout.js, src/detail-panels/lists/list-view.js, src/detail-panels/lists/lists.js, src/types.d.ts
Correctly displays the owner account for lists tab, and re-enables handle history
=> Fix display of lists and handle history

package-lock.json, package.json, src/api/blocklist.js, src/app.js, src/detail-panels/block-panel-generic/block-panel-generic.js
For some reason when I added react-query over the weekend I didn't end up with the latest version! Oops!
=> upgrade to the latest version of react-query

package-lock.json, package.json, src/api/resolve-handle-or-did.js
batches lookups for profiles up to 25 accounts at a time
closes #154
=> batch profile lookups

static/index.html
Includes only #161 to fix asset inclusion
=> Merge to main

src/api/blocklist.js, src/api/core.js, src/api/lists.js, src/detail-panels/block-panel-generic/block-panel-generic.js, src/detail-panels/blocked-by/index.js, src/detail-panels/blocking/index.js, src/detail-panels/lists/lists.js
This currently won't work as the new endpoints are only available in the api staging environment, and that env can't be reached due to missing CORS headers.
=> Display totals for lists and blocklists using standalone API endpoints

src/api/blocklist.js, src/api/core.js, src/api/dashboard-stats.js, src/api/handle-history.js, src/api/index.js, src/landing/home-stats/home-stats-table.js, src/types.d.ts
- Removes the x-api-key header from requests to stop making preflight reqs
- Adds handling for the stats endpoints periodically returning empty data
=> Random UI cleanup tasks

package-lock.json, src/cookie-policy.html, src/privacy-policy.html, src/terms-and-conditions.html, src/test.html
Only adding html files to src.
=> Policy readd

src/common-components/account-short-entry.jsx, src/detail-panels/lists/list-view.jsx
=> Add link to account name in lists

src/detail-panels/account-header/account-extra-info.jsx
=> add hyperlinks

src/api/placement.js, src/common-components/account-info-shared.css, src/detail-panels/account-header/account-header.jsx
=> Add placement in profile landing page

src/detail-panels/account-header/handle-history/handle-history.css
=> add word wrap to handle history

src/landing/about/about.jsx
add Clearsky status page link to top row hyperlinks
=> add status link to top row hyperlinks

src/api/blocklist.js, src/api/core.js, src/api/dashboard-stats-base.json, src/api/dashboard-stats.js, src/landing/home-stats/home-stats-table.jsx, src/landing/home-stats/index.jsx, src/landing/home-stats/infographics/top-blocked.jsx, src/landing/home-stats/infographics/top-blockers.jsx, src/landing/home-stats/infographics/top-list.jsx, src/types.d.ts
Updated code to handle new top lists data format.
https://github.com/user-attachments/assets/6fa17f3b-9622-4871-9e6c-923c9843408d
=> Update top lists parsing #229

src/common-components/account-info-shared.css, src/detail-panels/account-header/account-extra-info.css, src/detail-panels/account-header/account-header.jsx
Fixing the overlap in https://github.com/ClearskyApp06/ClearskyUI/issues/231
- move to a new line
- add a label (for context, but open to suggestions on the name)
- css tweak for spacing
=> Fix spacing issue for placement

src/api/labled.js, src/api/resolve-handle-or-did.js, src/detail-panels/account-header/account-extra-info.jsx, src/detail-panels/account-header/account-labels.jsx, src/detail-panels/labeled/index.jsx, src/detail-panels/labeled/labeled.css, src/detail-panels/layout.jsx, src/detail-panels/lists/list-view.jsx, src/detail-panels/lists/lists.css, src/detail-panels/lists/lists.jsx, src/detail-panels/tab-selector.jsx, src/types.d.ts
=> Labels view

src/api/labled.js, src/detail-panels/labeled/index.jsx
this will also fix the crash we're seeing when our current dev branch queries against the prod api without a return added for the all the labelers
=> simplify label fetch greatly

package-lock.json, package.json, src/landing/about/about.jsx
Removed the petition link from the about section
Resolves #283
=> Remove petition link

src/common-components/conditional-anchor.jsx, src/detail-panels/lists/list-view.jsx, src/detail-panels/packs/pack-view.jsx
Adds a component for generic user : ConditionalAnchor
This component accepts a condition argument. If at runtime the condition is Truthy, it renders an anchor (<a/>) entity, with the relevant link. Otherwise it renders a div in lieu.
This also handles :
https://github.com/ClearskyApp06/ClearskyUI/issues/251
=> 285 add conditional anchor component

src/api/index.js, src/api/resolve-handle-or-did.js, src/api/resolve/did-to-profile.js, src/api/resolve/handle-to-did.js, src/common-components/conditional-anchor.jsx, src/detail-panels/history/post/render-post.jsx, src/detail-panels/layout.css, src/detail-panels/packs/pack-view.jsx
- there was a react error being thrown because we were conditionally calling a hook
- our biggest, scariest part of the app was probably the profile resolution api stuff. that's all much better organized and documented (and with a couple of very minor bugs fixed too)
- removed a really spammy console log line
- removed the double scroll causing issues for mobile (may have more work to do here still, but it's like... 95% better)
- made the desktop layout sidebar/tabs not resize as various content loads in
=> Fix lots of papercut issues around the app

src/landing/about/about.css, src/landing/home.css
=> Fix Version leak on mobile

package-lock.json, src/common-components/format-timestamp.jsx, src/detail-panels/account-header/handle-history/handle-history.jsx
Rephrased the account history section.
=> Handle history wording issue#179

src/app.css, src/app.jsx, src/detail-panels/tab-selector.jsx
=> Move copyright watermark location

package-lock.json, package.json
=> upgrade vite

package-lock.json, src/detail-panels/blocking/index.jsx
This PR fixes the blocking count showing 0 while still waiting on request to return the number of blocked accounts 
Closes #334
=> fix blocking count showing 0 while waiting for request

package-lock.json, src/detail-panels/layout.css, src/detail-panels/layout.jsx, src/detail-panels/tabs.css, src/donate.css
Fixes #309
This PR Removes sticky behavior from the profile section while keeping tabs fixed on scroll
=> feat: remove profile sticky and keep tabs sticky
