- package.json
This will change a the behavior of all sorts of modules including React (disables behaviors of its StrictMode wrapper among other things).
> put react into production mode when building

- package-lock.json
- package.json
- src/api/blocklist.js
- src/api/index.js
- src/app.js
- src/common-components/visible.js
- src/detail-panels/block-panel-generic/block-panel-generic.js
- src/detail-panels/blocked-by/index.js
- src/detail-panels/blocking/index.js
- tsconfig.json
This switches over to react-query (aka tanstack query) to manage fetch/cache behavior of blocklists. Only one page will load initially. If more pages are available, the next will begin loading after a user scrolls to the bottom of the current list.
This also removes the search functionality, as it will be inaccurate as long as we aren't loading the complete list of blocks in the client. In the future we can restore search behavior somehow, ideally via server-side call, but perhaps conditionally whenever all pages have been loaded?
Closes #80 
Closes #59
Begins progress on #122
> react-query for blocklist fetching and caching

- src/detail-panels/block-panel-generic/block-panel-generic.js
This should prevent the “blocklist is undefined” error reported in discord by always making sure blocklist is defined!
> blocklist should always be an array

- src/api/blocklist.js
- src/api/pds.js
- src/api/resolve-handle-or-did.js
- src/detail-panels/block-panel-generic/block-panel-generic.js
- src/detail-panels/block-panel-generic/list-view.js
- src/detail-panels/blocked-by/index.js
- src/detail-panels/blocking/index.js
As discussed in discord previously, the query for blocklist is [perhaps the biggest problem facing the database](https://discord.com/channels/1309769535888429098/1309769535888429101/1310497760352538655) right now. This completely removes that query from being used in the UI, instead [going directly to a user's own PDS](https://discord.com/channels/1309769535888429098/1310042550429810832/1310230319177404437) to retrieve their list of blocked users.
> resolve blocklists directly from a user's pds

- src/api/lists.js
my upgrade to the react-query library forces a slight change to the params passed in the new paginated list query
> list query fixes for react-query@5

- src/landing/home.js
note that even when persisted to the url, these weren't correctly restored to the search input (in the event of a page refresh, or being deep-linked directly to clearsky with a `?q=` param), so adding the search term to the location wasn't useful for anything whatsoever
fixes #151
> Remove search terms from browser history

- src/api/dashboard-stats-base.json
- src/api/dashboard-stats.js
- src/landing/home-stats/home-stats-table.js
- src/types.d.ts
Without providing `initialDataUpdatedAt` it was going to take 5m before the preloaded stats were marked stale and live stats would be fetched 😅 
Also I now had to test with real data from the API and realized the data shape wasn't quite right.
> fix and actually fetch dashboard stats

- src/api/dashboard-stats.js
- src/landing/home-stats/home-stats-table.js
- src/landing/home-stats/index.js
- Remove "as of" field in stats detail view
- Maybe make it a greyed out placement somewhere, but NOT in the grid view.
- Removes a conditional in HomeStatsTable that would add the "as of" row.
- *Fix:* Updates a return value in the dashboard stats API to use a fallback "as of" date from initialData.
This "as of" row will be removed from the HomeStatsTable.
> Remove "as of" field from HomeStatsTable

- src/common-components/format-timestamp.js
- src/detail-panels/history/post/render-post.js
A stray `@ts-ignore` was hiding a bug from our TS check that was breaking post permalinks. I also noticed that avatars weren't resolving correctly for posts in reply to others, also as a result of a lack of typing, so I fixed that too.
> Fix timestamp permalinks and reply-to indicators

- src/detail-panels/account-header/account-header.jsx
the placement of toLocaleString in the last commit of  
[187-add-placement-to-account-info](https://github.com/seanmunson/ClearskyUI/tree/187-add-placement-to-account-info)
introduced an improperly resolved nullity potential. 
This should resolve it by evaluating the value before trying to cast it to local format
> 187 make locale string for placement less volatile

- src/detail-panels/lists/lists.jsx
I updated the conditional rendering to fix the list count header bug.
The first search is what's currently deployed, and the second search is the fix on my local.
https://github.com/user-attachments/assets/0d3a6e10-de52-4432-885a-6ceafc43ef40
> List count load in sequence #222 

- src/app.jsx
- src/common-components/error-boundary.jsx
- src/detail-panels/account-header/account-header.jsx
- src/detail-panels/index.js
- src/landing/home.jsx
When any ordinary error happens users will see:
However, when we encounter the specific error raised in #244 the page will automatically reload, possibly without them even noticing. If that error then reoccurs immediately, rather than going into an infinite reload loop, they will see this instead:
fixes #244
> Add a global error handler

- src/api/core.js
You can now force the UI to use either `staging` or `prod` API endpoints by adding a query param when the page loads:
`https://clearsky.app/?api=staging` will load prod UI but use the staging api endpoint
`https://dev.clearskyui.pages.dev/?api=prod` will load the staging UI and use prod API endpoint
> add option to override api endpoint

- package-lock.json
- readme.md
- src/app.jsx
- Updates readme based on linter
- This isn't necessary, but I like to use a very particular markdown linter (it hates spaces at the end of a line, amongst other things).
- Updates packages to resolve a high vuln
- Ran `npm update` for 2 specific packages, not on the entire package library. Hence the smaller package-lock update.
- `npm audit` will now show 0 vulns (constant vigilance is needed, of course)
- Copyright tag change from 2024 to 2025
- We in the future now woot woot!
> Update packages, readme, and copyright year

- src/detail-panels/lists/list-view.jsx
- src/types.d.ts
Adds in potential spam flag and source for list entries. Resolves #276 
- Increases opacity for any list flagged as potential spam
- Tried to do this on the parent code only but kept botching the override. Feel free to cleanup if you want. I'll knock the JS/TS dust off eventually.
- Adds tooltip to potential spam list entries to flag source
- Activate by clicking on the info icon for these potential spam list entries.
- Modifies types to reflect new endpoint fields. Allows for null.
- Removes row className for the title of the list entry.
- I left this commented out code in the PR. Removing the className helps with a whitespace/horizontal scroll issue that I'm currently experiencing on mobile. Please test this on your end to make sure this hasn't botched anything else up on the list view.
> Adding front end display of list potential spam flagging.

- src/detail-panels/history/search-header.css
- src/detail-panels/layout.css
- src/detail-panels/layout.jsx
Ensures the content scrolls to the top when switching tabs.
Added logic to reset scroll position using key prop.
> Fix scroll reset issue on tab switch for content container

- package-lock.json
- package.json
- src/api/lists.js
- src/common-components/account-short-entry.jsx
- src/common-components/progressive-render.jsx
- src/detail-panels/block-panel-generic/list-view.jsx
- src/detail-panels/lists/list-view.css
- src/detail-panels/lists/list-view.jsx
- src/detail-panels/lists/lists.jsx
- vite.config.mjs
Withheld working on the virtualisation element to get a viable working product out.
Throttled getListSize to prevent server overload.
Updated with css changes from #264.
List count appears to the right of of the list name.
resolves #255.
> Without virtualisation

- package-lock.json
- package.json
- src/api/lists.js
- src/common-components/account-short-entry.jsx
- src/detail-panels/lists/list-view.css
- src/detail-panels/lists/list-view.jsx
- src/detail-panels/lists/lists.jsx
- vite.config.mjs
@noahm , addressed the virtualisation suggestion by implementing React Windows, only a subset of the lists are rendered at a time now.  Additionally, used lodash's throttling functionality to minimise the frequency of the requests as it'd overload the servers.
Both appear fine, however, an issue remains in that the value returned useListSize is always '1'. That wasn't always the case as I'd initially tested the endpoint provided by @thieflord06 on Postman and would get varied results depending on the url provided however whether via Postman, or the app itself, it now always returns 1. Unsure why that may be, any suggestions?
> virtualized list with react window & throttled the request to prevent 429 errors // add list counts to list view

- src/detail-panels/account-header/account-extra-info.jsx
- src/detail-panels/layout.css
- src/detail-panels/layout.jsx
in mobile mode, "details" now becomes a pop-out that can be triggered by tapping the (i) button in the header
https://github.com/ClearskyApp06/ClearskyUI/issues/296
> Make profile top better in mobile mode

- .github/workflows/npm.yaml
- eslint.config.mjs
- package-lock.json
- package.json
- src/api/index.js
- src/common-components/account-short-entry.jsx
- src/common-components/visible.jsx
- src/detail-panels/account-header/account-extra-info.jsx
- src/detail-panels/account-header/account-header.jsx
- src/detail-panels/block-panel-generic/block-list-panel-generic.jsx
- src/detail-panels/block-panel-generic/block-panel-generic.jsx
- src/detail-panels/history/history-scrollable-list.jsx
- src/detail-panels/history/post/post-embed.jsx
- src/detail-panels/history/post/render-post.jsx
- src/detail-panels/labeled/index.jsx
- src/landing/about/about.jsx
- src/landing/home-stats/infographics/face-icon.jsx
- src/landing/logo.jsx
The most important part of having eslint here is the checks in `eslint-plugin-react-hooks` which help check some of the most critical usage patterns when it comes to writing React code.
> Add eslint to help maintain higher code standards

- src/api/packs.js
- src/common-components/visible.jsx
the Visible component was previously breaking several rules of how you should use react at once, and managing to work as intended with the combination of bad things it was doing. after adding the linter it identified the bad things. I previously fixed one and ignored the other: https://github.com/ClearskyApp06/ClearskyUI/commit/566951d97871bfced8134f45fe0e0fd07e9b8106#diff-66b34b935fda5fd20aada030042ddee176aa4854cac57b9ee88b8b8ec2fb053e
This reduced it to only breaking one rule, and ended up breaking how the component worked as a result.
fixes #333
> correctly pass deps to useEffect in Visible component

- src/api/search/search-handle.js
Fixes #325 
This PR fixes a TypeError that occurred during autocomplete when the input included dot-separated values (eg:priya.bsky) 
When entering inputs like this into the search bar, the app throws a TypeError and fails to fetch results. This happens because the input isn't being split correctly the period (.) is treated as part of the word rather than a delimiter.
So to fix this issue replacing split(/\s+/) with .split(/[\s.]+/) ensure that both whitespace and dot separates the inputs into ["priya", "bsky", "social"] The issue happened because inputs like priya.bsky were treated as full website URLs, which caused the fetch to fail. This fix updates the splitting logic to break down those inputs correctly
> TypeError in autocomplete

- src/api/core.js
- src/api/useAdTracking.js
- src/common-components/block-lists-view.jsx
- src/common-components/first-party-ad.jsx
- src/common-components/google-ad-slot.jsx
- src/common-components/progressive-render.jsx
- src/detail-panels/account-header/account-extra-info.css
- src/detail-panels/account-header/account-extra-info.jsx
- src/detail-panels/account-header/account-header.jsx
- src/detail-panels/block-panel-generic/list-view.jsx
- src/detail-panels/history/search/render-search-results.jsx
- src/detail-panels/labeled/index.jsx
- src/detail-panels/layout.css
- src/detail-panels/layout.jsx
- src/detail-panels/lists/list-view.jsx
- src/detail-panels/packs/pack-view.jsx
- src/donate.css
- src/landing/home-header.jsx
- src/landing/home.css
- src/landing/home.jsx
This PR adds full integration for Google AdSense ads and improves the existing FirstPartyAd component. Ads now work responsively across desktop and mobile, and click tracking is implemented with proper payloads.
- **AdSlot Component**
- Reusable Google AdSense component with support for `auto`, `fluid`, and optional `layoutKey` for in-feed ads.
- Development placeholder prevents 403 errors on localhost.
- Handles single `adsbygoogle.push()` call per ad instance to avoid duplicate ad errors.
- **FirstPartyAd Component**
- Responsive container while preserving original image size.
- Images scale down if larger than container, maintaining aspect ratio.
- Click tracking sends `adId` and `placementId` in the payload.
- **PropTypes & Documentation**
- Added PropTypes and JSDoc for all ad …
> Integrate Google AdSense and FirstPartyAd Components
